dist: bionic
os: linux

git:
  depth: 150

env:
  global:
  - CACHE_DIR="$HOME/misc_cache"
  - MINICONDA_DIR="$HOME/miniconda"
  - PYTHONIOENCODING=UTF8
  - BOTO_CONFIG=/dev/null # bogus value to override config on travis

cache:
  directories:
    - $HOME/misc_cache
    - $HOME/miniconda
  timeout: 1000

jobs:
  fast_finish: true
  include:

    - language: java
      jdk: openjdk8
      stage: build
      env:
        - TRAVIS_JOB=build_dxWDL
        # DX_API_TOKEN (for DNAnexus builds)
        - secure: "A6aQZE2dtzZB8NRIjE5uRa0S0RdDubpAp7ONmT5arOj7MqMU5ZWOGPkELwE/wyVD0dfI3k2+jSbjMzK3LYuRexaPXnXFxgiTI4eGEk/V02D/aUTiwe0IqAKjRPZs57NmixNzJWhOkunKPc2V7N4vQdq7AOHgHZOBaMb/oJeuOcSJZHiUa+Tk5PptL3FGixGOvPqCPP8wmNp4+rp3SsWzsWvLlDo5FtZfHMtvekjCpWBeArnxWAyddHUu+2YzllMtX4eqCqi4ztq0wJzHzIAkXdh/A+zjm9KawQCLza4LvW8AL1pX4Wrq7jwxc7qtR1hyBD2OFJRpulvp5Qf077RH18Wme+B2OOEtnrDMrtaKo1R4QzNpj3WH25J3OCcW6usjtAwIjpnSd3OFCEvr88hSMV/UAPHddjrXGLBBbZUpSzD45o/bY5101hNLNFHWRc3CPuWwfHhAKaxNZ+AbGJXlpHkNhSiZ6noZvouwv5hwR8CX3CmyrcAdIpEayGWVQSXeheN9bl7+23MJy2j/wnKPRtMArAj8dHgwvIfBggX5daROiYxVMhY4G9UqBo8xUlw+EJrWRAM1id5L1O1y44T8bVxd4WqkJAY7SwOhcXZ4KrkVWdVDxElWWMN7vWj7qxYRYrQpkOqlrSExtTNyIHecfDvgIEuYHdR0qB+sSWw+7CM="
        - DX_PROJECT=project-F856jv809y3VkzyFGkKqX367
      install:
        - travis/install-wdl.sh
      script:
        - travis/version-wdl-runtimes.sh
        - travis/validate-wdl.sh
        - travis/build-dx.sh

    - language: java
      jdk: openjdk8
      stage: test
      env:
        - TRAVIS_JOB=test_cromwell
      install:
        - DOCKER_TAG=`travis/list-docker-tags.sh | tail -1`
        - docker pull $DOCKER_TAG
        - travis/install-wdl.sh
      script:
        - travis/version-wdl-runtimes.sh
        - travis/validate-wdl.sh
        - travis/tests-cromwell.sh

    #- language: generic
    #  stage: test
    #  env:
    #    - TRAVIS_JOB=build_conda_in_docker
    #    # $ANACONDA_TOKEN for uploading builds to anaconda.org ("broad-viral" channel)
    #    - secure: "cDKRuVUr2NMZk933RHMMYKDCfU2gZfe3VJLNG82zsj47rrfoRzUsDny71v27OuydgjICiBWGuFAl4alNBVkzQWGt7G1DaFVLn48SwqtnG4u0KAUVX32b/0sw7OrXRDDqD5pr5Q8J59xwxSKQmmXFXlMbZpSEeREf8c3Yn6pvm2c="
    #  install:
    #    - DOCKER_TAG=`travis/list-docker-tags.sh | tail -1`
    #    - docker pull $DOCKER_TAG
    #    - travis/install-gatk.sh
    #  script:
    #    - docker run -v $GATK_PATH:/gatk -e _JAVA_OPTIONS -e TRAVIS_BRANCH -e TRAVIS_PULL_REQUEST -e TRAVIS_TAG -e TRAVIS_COMMIT -e ANACONDA_TOKEN --entrypoint /bin/bash $DOCKER_TAG -c 'set -e; cd /opt/viral-ngs/source; gatk3-register /gatk/GenomeAnalysisTK.jar; travis/install-conda-build.sh; travis/build-conda.sh'

