dist: bionic
os: linux

git:
  depth: 150

env:
  global:
  - CACHE_DIR="$HOME/misc_cache"
  - MINICONDA_DIR="$HOME/miniconda"
  - PYTHONIOENCODING=UTF8
  - BOTO_CONFIG=/dev/null # bogus value to override config on travis

cache:
  directories:
    - $HOME/misc_cache
    - $HOME/miniconda
  timeout: 1000

jobs:
  fast_finish: true
  include:

    - language: java
      jdk: openjdk11
      stage: validate
      env:
        - TRAVIS_JOB=validate_WDL
      install:
        - travis/install-wdl.sh
      script:
        - travis/validate-wdl.sh

    - language: java
      jdk: openjdk11
      stage: build
      env:
        - TRAVIS_JOB=build_dxWDL
        # DX_API_TOKEN (for DNAnexus builds) -- token #2, expires 12/31/2024
        - secure: "EYyJTY20ZV3RehLmBYiZ1sWyBtLMIOGWSkN8a+Ez0PUA2CirKH9GlUFKMfujKOvrro9BYfgng0F6pQaMh9yarQUEIh7nv6zF/+LjPfNpddTY5zd8MJPtoB133uxw18cOkVcmHgxwVrN1aSuO96pWeENhr6FNt5EY5glfzgUvvASILJWRYBoq48YTjmXYA/LOG39gRzjquhxX3lelZpgLujXwLgTH2MR1MziKNfMdeHrJ/WvPZsATjhvSa9/KOO+HFYyHtHMuRCPAmGV0ZjIkpOthUtoG3ck5r5Z8Z6nGCS4b2qJ+uexWExrd7TBwMcpKI6wQlX15ZcZm8mAdC/KUX2eKbtjSYD68ZE/pg77I5inJex0l2suQtMBPxUl4SPK/d+GsnoL9+rGOdDVdgO/RUg+PoIYLcivjk/q2Et4LBS0IqIhe+/SOE3n70gHYMUFiGh2gCdrgyy0/YBfkAt95wtnjA+nSpqZ6lCUnUE5nT5Krs8beiYqCk9yYDF0YWTlwmezi7Jgx7PLuuTmNEScvfV/l2yKut/kVuAoMI6KEmpfeSNFEjIsrIvW9Fbq71Y1H8q+Ex27l3GR/OhrVQSeYaIN5BwVEI353DcRDiSmi4iwsmYLL2x9Q+7qPTadwMOeIU999WiYqk9gH+vk/86hUg2vA7MlKYmzD0G95sxNSFkI="
        - DX_PROJECT=project-F856jv809y3VkzyFGkKqX367
      install:
        - travis/install-wdl.sh
      script:
        - echo travis/build-dx.sh

    - language: java
      jdk: openjdk11
      stage: build
      env:
        - TRAVIS_JOB=test_cromwell
      install:
        - travis/install-wdl.sh
      script:
        - travis/tests-cromwell.sh

    #- language: generic
    #  stage: build
    #  env:
    #    - TRAVIS_JOB=build_conda_in_docker
    #    # $ANACONDA_TOKEN for uploading builds to anaconda.org ("broad-viral" channel)
    #    - secure: "cDKRuVUr2NMZk933RHMMYKDCfU2gZfe3VJLNG82zsj47rrfoRzUsDny71v27OuydgjICiBWGuFAl4alNBVkzQWGt7G1DaFVLn48SwqtnG4u0KAUVX32b/0sw7OrXRDDqD5pr5Q8J59xwxSKQmmXFXlMbZpSEeREf8c3Yn6pvm2c="
    #  install:
    #    - DOCKER_TAG=`travis/list-docker-tags.sh | tail -1`
    #    - docker pull $DOCKER_TAG
    #    - travis/install-gatk.sh
    #  script:
    #    - docker run -v $GATK_PATH:/gatk -e _JAVA_OPTIONS -e TRAVIS_BRANCH -e TRAVIS_PULL_REQUEST -e TRAVIS_TAG -e TRAVIS_COMMIT -e ANACONDA_TOKEN --entrypoint /bin/bash $DOCKER_TAG -c 'set -e; cd /opt/viral-ngs/source; gatk3-register /gatk/GenomeAnalysisTK.jar; travis/install-conda-build.sh; travis/build-conda.sh'

